version: '3'

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  