version: '3'

volumes:
  production_caddy: {}

services:

  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    image: wedding_production_caddy
    volumes:
      - production_caddy:/root/.caddy
    env_file:
      - ./.envs/.production/.caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      


